services:
  - type: web
    name: parcial-cryptovision
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Parcial.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
